name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # This ensures the workflow only runs when a tag is pushed

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write
    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v2
        with:
          name: release-dists
          path: dist/

      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@v2
        with:
          packages-dir: dist/
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
